services:
  createveai-nexus-server:
    container_name: createveai-nexus-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 43080:43080
    volumes:
      - ./logs:/app/logs
      - ./processing:/app/processing
      - ./custom_apis:/app/custom_apis
